import { COUNTRIES, V4_BASE64, V6_BASE64 } from './geo-table'

/**
 * Address -> country, offline.
 *
 * The table this reads is generated by `scripts/update-geoip.ts`, which is
 * where the reasoning about the data source lives. The short version: it is
 * registry allocation data baked into the build, so no visitor address is ever
 * sent anywhere to be resolved, and the answer is a country and nothing finer.
 *
 * Pure, like the rest of `track.ts` - one string in, two letters or null out -
 * so the interesting cases are testable without a request.
 */

/** ISO-3166 alpha-2, or null when the address is not one we can place. */
export type Country = string | null

/**
 * The packed tables, decoded once on first use.
 *
 * Lazily, because the two buffers are about 2 MB and every process that imports
 * this module for its types - a test, a build step, the client bundle's tracer -
 * would otherwise pay for them. The first beacon of the process pays instead.
 */
let v4: Buffer | null = null
let v6: Buffer | null = null

const V4_WIDTH = 5 // uint32 start + uint8 country
const V6_WIDTH = 9 // uint64 start + uint8 country

/**
 * Blocks that describe the network rather than a person.
 *
 * A private or loopback address means the proxy in front of us did not pass the
 * real one through, and a carrier-grade NAT address belongs to the carrier's
 * pool rather than to a place. None of these are in the registry table anyway;
 * rejecting them here says so out loud and skips the search.
 */
function isPrivateV4(ip: number): boolean {
  const a = ip >>> 24
  const b = (ip >>> 16) & 0xff
  return (
    a === 0 || // this network
    a === 10 || // RFC 1918
    a === 127 || // loopback
    (a === 100 && b >= 64 && b < 128) || // RFC 6598 carrier-grade NAT
    (a === 169 && b === 254) || // link-local
    (a === 172 && b >= 16 && b < 32) || // RFC 1918
    (a === 192 && b === 168) || // RFC 1918
    a >= 224 // multicast and reserved
  )
}

/** Dotted quad -> uint32, or null if it is not one. */
export function parseIpv4(text: string): number | null {
  const parts = text.split('.')
  if (parts.length !== 4) return null
  let value = 0
  for (const part of parts) {
    // Rejected rather than coerced: `Number('')` is 0 and `Number('1e2')` is
    // 100, and neither of those is an octet anybody typed.
    if (!/^\d{1,3}$/.test(part)) return null
    const octet = Number(part)
    if (octet > 255) return null
    value = value * 256 + octet
  }
  return value
}

/**
 * IPv6 -> its top 64 bits, which is the resolution the table stores.
 *
 * Returns null for an IPv4-mapped address (`::ffff:1.2.3.4`) so the caller can
 * fall back to the v4 table, where that address actually lives.
 */
export function parseIpv6Prefix(text: string): bigint | null {
  const bare = text.split('%')[0] ?? '' // strip a zone id, e.g. fe80::1%eth0
  if (!bare.includes(':')) return null

  const halves = bare.split('::')
  if (halves.length > 2) return null

  const head = halves[0] ? halves[0].split(':') : []
  const tail = halves.length === 2 && halves[1] ? halves[1].split(':') : []

  // A trailing dotted quad occupies the last two groups.
  const last = tail.length ? tail[tail.length - 1] : head[head.length - 1]
  let embedded: number[] = []
  if (last?.includes('.')) {
    const mapped = parseIpv4(last)
    if (mapped === null) return null
    embedded = [(mapped >>> 16) & 0xffff, mapped & 0xffff]
    if (tail.length) tail.pop()
    else head.pop()
  }

  const fill = 8 - head.length - tail.length - embedded.length
  if (halves.length === 1 ? fill !== 0 : fill < 0) return null

  const groups = [...head, ...Array(halves.length === 2 ? fill : 0).fill('0'), ...tail]
  const numbers: number[] = []
  for (const group of groups) {
    if (!/^[0-9a-fA-F]{1,4}$/.test(group)) return null
    numbers.push(parseInt(group, 16))
  }
  numbers.push(...embedded)
  if (numbers.length !== 8) return null

  // `::ffff:a.b.c.d` is an IPv4 address wearing an IPv6 coat. Saying so lets
  // the caller look it up where it is, instead of missing the v6 table.
  const isMapped = numbers.slice(0, 5).every((n) => n === 0) && numbers[5] === 0xffff
  if (isMapped) return null

  return numbers.slice(0, 4).reduce((acc, group) => (acc << 16n) | BigInt(group), 0n)
}

/**
 * The last entry whose start is at or below `target`.
 *
 * Every address between one start and the next belongs to the same allocation,
 * so this single search is the whole lookup - there is no second comparison
 * against an end, because the next entry's start *is* the end.
 */
function search(table: Buffer, width: number, read: (at: number) => bigint, target: bigint): number {
  let low = 0
  let high = table.length / width - 1
  let found = -1

  while (low <= high) {
    const mid = (low + high) >> 1
    if (read(mid * width) <= target) {
      found = mid
      low = mid + 1
    } else {
      high = mid - 1
    }
  }

  if (found < 0) return 0
  return table.readUInt8(found * width + width - 1)
}

/**
 * Where an address was registered, or null.
 *
 * Null is the honest answer for a lot of input - a private address, an address
 * in a gap between allocations, an unparseable header - and every one of those
 * is stored as unknown rather than guessed at.
 */
export function countryForIp(ip: string | null): Country {
  const text = ip?.trim()
  if (!text || text === 'unknown') return null

  // A v6 address in a URL or header can arrive bracketed.
  const bare = text.startsWith('[') ? text.slice(1, text.indexOf(']')) : text

  let index: number

  const asV4 = parseIpv4(bare)
  if (asV4 !== null) {
    if (isPrivateV4(asV4)) return null
    v4 ??= Buffer.from(V4_BASE64, 'base64')
    const table = v4
    index = search(table, V4_WIDTH, (at) => BigInt(table.readUInt32BE(at)), BigInt(asV4))
  } else {
    const asV6 = parseIpv6Prefix(bare)
    if (asV6 === null) {
      // Not v6 either - unless it was a mapped v4, which parses as v4 once the
      // prefix is off.
      const mapped = bare.includes('.') ? parseIpv4(bare.slice(bare.lastIndexOf(':') + 1)) : null
      if (mapped === null || isPrivateV4(mapped)) return null
      v4 ??= Buffer.from(V4_BASE64, 'base64')
      const table = v4
      index = search(table, V4_WIDTH, (at) => BigInt(table.readUInt32BE(at)), BigInt(mapped))
    } else {
      // Loopback (::1), unique-local (fc00::/7) and link-local (fe80::/10).
      const top = asV6 >> 48n
      if (asV6 === 0n || (top >= 0xfc00n && top <= 0xfebfn)) return null
      v6 ??= Buffer.from(V6_BASE64, 'base64')
      const table = v6
      index = search(table, V6_WIDTH, (at) => table.readBigUInt64BE(at), asV6)
    }
  }

  return index === 0 ? null : (COUNTRIES[index - 1] ?? null)
}
