'use client'

import { useEffect, useRef } from 'react'

/**
 * The channel's mark: XO standing in front of a small universe.
 *
 * ---------------------------------------------------------------------------
 * What it is
 * ---------------------------------------------------------------------------
 * A wordmark, not an illustration. "XO · UNIVERSE" is set in the pixel face the
 * headlines and the nav use, and the planet is drawn *behind the two letters*
 * rather than beside them - the name is the picture, and the picture is what
 * makes the name mean a place rather than two initials.
 *
 * The letters are real text. A screen reader gets "XO · UNIVERSE" from the DOM,
 * the SVG behind them is `aria-hidden`, and a browser that draws no SVG at all
 * still shows the name in the right face.
 *
 * ---------------------------------------------------------------------------
 * The rotation, and what it is allowed to cost
 * ---------------------------------------------------------------------------
 * The globe turns towards the pointer. Three rules held it to something a
 * marketing page can afford:
 *
 *   1. No permanent animation frame. Nothing here runs on a loop - the only
 *      thing that ever schedules a frame is a pointer that has just moved, and
 *      one frame is scheduled per move at most however many events arrive.
 *      Between two moves this component costs nothing at all.
 *   2. Nothing while it is off screen. The listener is bound and unbound by an
 *      `IntersectionObserver`, so scrolling past the band takes the handler off
 *      the window rather than leaving it there testing a rectangle nobody can
 *      see. The band sits two thirds of the way down a long page, which is to
 *      say it is off screen for most of a visit.
 *   3. Reduced motion means a still picture, not a slower one. With the media
 *      query set the listener is never bound: the CSS variables keep their
 *      resting values and the mark is a static drawing. That is the honest
 *      reading of the preference here - the movement carries no information,
 *      so there is nothing to preserve a quieter version of.
 *
 * The handler writes CSS custom properties and stops. The interpolation is a
 * CSS transition on `transform`, which is what keeps this off the main thread
 * and out of a `requestAnimationFrame` loop of our own - see `.xo-mark-*` in
 * `globals.css` for the transforms those variables feed.
 *
 * No dependency, and deliberately no R3F: this is a marketing page that ships
 * no 3D runtime today, and a spinning planet is not the reason to start.
 *
 * ---------------------------------------------------------------------------
 * Why the file is not called `xo-universe-mark`
 * ---------------------------------------------------------------------------
 * Because `landing.tsx` imports it, which means it is on `.sync-to-public.txt`
 * and goes to the public repository - and `channel.test.ts` guards that list
 * by refusing any path with "xo-universe" in it. That net is coarser than the
 * rule it protects (the deny list is four folder prefixes, and this is in none
 * of them) but it is the right shape: the list is regenerated by hand from a
 * diff, and a name-based check is what catches the paste nobody read twice.
 *
 * There is nothing of the channel in here. It is a wordmark and a planet - the
 * story, its schedule and its routes stay on this side of the line, which is
 * why over there this draws a mark that no page ever passes an episode to.
 */

/** How far the mark leans, in degrees, at the edges of the viewport. */
const TILT = { x: 14, y: 26, spin: 40 } as const

function clamp(value: number) {
  return Math.max(-1, Math.min(1, value))
}

export function XoUniverseMark({ className = '' }: { className?: string }) {
  const ref = useRef<HTMLSpanElement>(null)

  useEffect(() => {
    const mark = ref.current
    if (!mark) return

    const still = window.matchMedia('(prefers-reduced-motion: reduce)')

    let bound = false
    let visible = false
    let frame = 0
    let pointer: { x: number; y: number } | null = null

    const write = () => {
      frame = 0
      if (!pointer) return
      // Measured here rather than cached: the page scrolls, and a rectangle
      // read once at bind time would have the globe leaning at whatever the
      // pointer meant several screens ago. One read per frame, on one element,
      // and only while somebody is actually moving a pointer over the band.
      const box = mark.getBoundingClientRect()
      const dx = clamp((pointer.x - (box.left + box.width / 2)) / (window.innerWidth / 2))
      const dy = clamp((pointer.y - (box.top + box.height / 2)) / (window.innerHeight / 2))

      mark.style.setProperty('--xo-ry', `${(dx * TILT.y).toFixed(2)}deg`)
      mark.style.setProperty('--xo-rx', `${(-dy * TILT.x).toFixed(2)}deg`)
      mark.style.setProperty('--xo-spin', `${(dx * TILT.spin).toFixed(2)}deg`)
      // The star field slides the other way. Two layers moving in opposite
      // directions is the whole of the depth here, and it is cheaper than
      // anything that would actually have depth.
      mark.style.setProperty('--xo-drift-x', `${(-dx * 6).toFixed(2)}px`)
      mark.style.setProperty('--xo-drift-y', `${(-dy * 6).toFixed(2)}px`)
    }

    const onMove = (event: PointerEvent) => {
      pointer = { x: event.clientX, y: event.clientY }
      // Coalesced: a pointer can fire a dozen moves between two frames and the
      // only one that could be drawn is the last.
      if (!frame) frame = requestAnimationFrame(write)
    }

    const sync = () => {
      const wanted = visible && !still.matches
      if (wanted === bound) return
      bound = wanted
      if (wanted) {
        window.addEventListener('pointermove', onMove, { passive: true })
        return
      }
      window.removeEventListener('pointermove', onMove)
      if (frame) cancelAnimationFrame(frame)
      frame = 0
    }

    const watch = new IntersectionObserver((entries) => {
      visible = entries.some((entry) => entry.isIntersecting)
      sync()
    })
    watch.observe(mark)
    // Somebody turning the preference on mid-visit gets the still version
    // immediately rather than the next time they scroll past.
    still.addEventListener('change', sync)

    return () => {
      watch.disconnect()
      still.removeEventListener('change', sync)
      visible = false
      sync()
    }
  }, [])

  return (
    <span ref={ref} className={`xo-mark ${className}`}>
      <span className="xo-mark-globe">
        {/* Decoration. The name beside it is the content, and a screen reader
            announcing "circle, ellipse, ellipse" is the texture being read
            out loud. */}
        <svg className="xo-mark-sky" viewBox="0 0 120 120" aria-hidden="true">
          <defs>
            <radialGradient id="xo-mark-body" cx="38%" cy="32%" r="78%">
              <stop offset="0%" stopColor="oklch(0.78 0.19 330)" />
              <stop offset="55%" stopColor="oklch(0.5 0.2 325)" />
              <stop offset="100%" stopColor="oklch(0.26 0.13 285)" />
            </radialGradient>
            {/* The meridians are drawn as whole ellipses and cut to the disc,
                which is what stops them hanging off the edge of the planet
                when the group is turned. */}
            <clipPath id="xo-mark-disc">
              <circle cx="60" cy="60" r="30" />
            </clipPath>
          </defs>

          <g className="xo-mark-stars">
            <circle cx="14" cy="22" r="1.6" />
            <circle cx="102" cy="18" r="1.2" />
            <circle cx="112" cy="86" r="1.7" />
            <circle cx="24" cy="98" r="1.3" />
            <circle cx="8" cy="62" r="1" />
            <circle cx="96" cy="108" r="1" />
            <circle cx="70" cy="10" r="1.1" />
          </g>

          {/* The ring and the moon on it turn together: the moon is what makes
              the spin readable at all, since a ring rotating about its own
              centre looks identical at every angle. */}
          <g className="xo-mark-orbit">
            <ellipse cx="60" cy="60" rx="52" ry="17" />
            <circle className="xo-mark-moon" cx="112" cy="60" r="3.4" />
          </g>

          <circle className="xo-mark-planet" cx="60" cy="60" r="30" />

          <g className="xo-mark-grid" clipPath="url(#xo-mark-disc)">
            <ellipse cx="60" cy="60" rx="10" ry="30" />
            <ellipse cx="60" cy="60" rx="22" ry="30" />
            <path d="M30 60h60M34 46h52M34 74h52" />
          </g>
        </svg>

        {/* Over the planet, and the reason the globe is only 30 units of a
            120 box: the letters have to sit on the body rather than on the
            ring, or the mark reads as two things that happen to overlap. */}
        <span className="xo-mark-xo font-pixel">XO</span>
      </span>

      <span className="xo-mark-sep" aria-hidden="true">
        ·
      </span>
      <span className="xo-mark-word font-pixel">UNIVERSE</span>
    </span>
  )
}
