/**
 * Lists every model we ship, so the world builder can offer all of them.
 *
 *     bun run scripts/build-catalogue.ts
 *
 * Run it after adding or removing an asset pack. The output is checked in.
 *
 * ---------------------------------------------------------------------------
 * Why this is generated and not read at runtime
 * ---------------------------------------------------------------------------
 * A route handler doing `readdir` would be shorter and would never go stale.
 * It would also be a server surface whose answer depends on the filesystem of
 * whichever container served it, and the builder needs the list in the browser
 * - to search it, to group it, to draw a thumbnail of each one - so a runtime
 * read means a fetch, a loading state and an error state for a list that only
 * changes when somebody downloads a new pack from itch.io.
 *
 * Checked in, the list is a plain import and a diff in the pull request shows
 * exactly which models arrived. The staleness risk is real and the test beside
 * the generated file is the answer to it: it walks `public/` and fails if the
 * two disagree.
 */

import { readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { PACK_ORDER, PACKS } from '@/domain/builder/packs'

const ROOT = path.join(import.meta.dir, '..')
const PUBLIC = path.join(ROOT, 'public')
const OUT = path.join(ROOT, 'src', 'domain', 'builder', 'catalogue.generated.ts')

/**
 * The model ids in one pack, sorted.
 *
 * Sorted rather than left in directory order because directory order is the
 * filesystem's business and differs between machines - which would make this
 * file churn in the diff every time somebody regenerated it on a different OS.
 */
export function readPack(packId: string): string[] {
  const pack = PACKS[packId]
  const dir = path.join(PUBLIC, pack.path)
  const names: string[] = []

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(pack.ext)) continue
    const bare = entry.name.slice(0, -pack.ext.length)
    // The peeps are all `animal-<name>`; the prefix lives in the URL, not the
    // id. Anything in that folder without the prefix is not a peep.
    if (pack.prefix) {
      if (!bare.startsWith(pack.prefix)) continue
      names.push(bare.slice(pack.prefix.length))
    } else {
      names.push(bare)
    }
  }

  return names.sort()
}

/** Every pack's ids, in `PACK_ORDER`. Exported so the drift test can reuse it. */
export function readCatalogue(): { packId: string; models: string[] }[] {
  return PACK_ORDER.map((packId) => ({ packId, models: readPack(packId) }))
}

function main(): void {
  const packs = readCatalogue()
  const total = packs.reduce((sum, pack) => sum + pack.models.length, 0)

  const body = packs
    .map(
      ({ packId, models }) =>
        `  ${JSON.stringify(packId)}: [\n${models
          .map((name) => `    ${JSON.stringify(name)},`)
          .join('\n')}\n  ],`,
    )
    .join('\n')

  writeFileSync(
    OUT,
    `// Generated by scripts/build-catalogue.ts. Do not edit by hand.
//
// ${total} models across ${packs.length} packs. Names only - the pack id is the
// key, and \`builderUrl\` in ./packs.ts turns the pair into a path.

export const PACK_MODELS: Record<string, readonly string[]> = {
${body}
}
`,
  )

  for (const { packId, models } of packs) {
    console.log(`${packId.padEnd(14)} ${String(models.length).padStart(5)}`)
  }
  console.log(`${'total'.padEnd(14)} ${String(total).padStart(5)}  ->  ${path.relative(ROOT, OUT)}`)
}

if (import.meta.main) main()
