/**
 * The store's picture of the Mau-Mau cartridge.
 *
 *     node scripts/maumau-cover.mjs
 *
 * ---------------------------------------------------------------------------
 * Composed rather than screenshotted, and that is the difference from boxing
 * ---------------------------------------------------------------------------
 * `scripts/boxing-cover.mjs` drives a real browser at a real match, because a
 * boxing cover is two animated fighters in a voxel ring and there is no way to
 * draw that without running it. A card game's cover is cards, and this project
 * already has all fifty-two of them in one atlas with a layout it can prove -
 * so a browser here would be three hundred megabytes of Chromium to arrange
 * seven rectangles.
 *
 * It is also the version that keeps working. The boxing cover needs a dev
 * server, a signed-in session and a running match; this needs
 * `packages/maumau/assets/cards-kaykit.png` and nothing else, so it can be
 * re-run on any checkout at any time.
 *
 * The hand it draws is fixed and is not a random deal: a cover that changed
 * every run is a cover nobody can tell has been regenerated by mistake. The
 * cards chosen are the game - a seven, an eight, a nine, a jack - so the
 * picture says what the specials are before anybody reads the blurb.
 */

import sharp from 'sharp'
import { join } from 'node:path'

import { KAYKIT, cellOf } from '../packages/maumau/src/art/deck.ts'

const SHEET = join(process.cwd(), 'packages', 'maumau', 'assets', KAYKIT.sheet)
const OUT = process.env.OUT ?? 'public/xp/shots/maumau.png'

const WIDTH = 1280
const HEIGHT = 720

/** The felt. Two greens, so the table has a middle rather than a flat wash. */
const FELT = `
<svg width="${WIDTH}" height="${HEIGHT}">
  <defs>
    <radialGradient id="felt" cx="50%" cy="46%" r="72%">
      <stop offset="0%" stop-color="#1d5c46"/>
      <stop offset="100%" stop-color="#0a2b21"/>
    </radialGradient>
  </defs>
  <rect width="${WIDTH}" height="${HEIGHT}" fill="url(#felt)"/>
</svg>`

/** One card off the atlas, at a size, rotated, with a shadow under it. */
async function card(name, width, angle) {
  const cell = name === 'back' ? KAYKIT.back : cellOf(name)
  const height = Math.round((width / KAYKIT.cell.width) * KAYKIT.cell.height)

  const face = await sharp(SHEET)
    .extract({
      left: cell.column * KAYKIT.cell.width,
      top: cell.row * KAYKIT.cell.height,
      width: KAYKIT.cell.width,
      height: KAYKIT.cell.height,
    })
    .resize(width, height, { fit: 'fill' })
    .png()
    .toBuffer()

  return sharp(face)
    .rotate(angle, { background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer()
}

/**
 * A hand fanned across the bottom, and the pile and the top card above it.
 *
 * Laid out by hand rather than by the game's own renderer: the cover is a
 * *picture of the game* and not a screenshot of one, so it can put the jack
 * where a jack reads best instead of where the rules would have left it.
 */
const FAN = [
  ['h7', -16],
  ['s8', -8],
  ['d9', 0],
  ['cJ', 8],
  ['hA', 16],
]

const cover = await sharp(Buffer.from(FELT)).png().toBuffer()

const pieces = []

// The draw pile and the card in play, above the hand.
pieces.push({
  input: await card('back', 175, -6),
  left: 400,
  top: 70,
})
pieces.push({
  input: await card('s8', 175, 4),
  left: 660,
  top: 70,
})

// The hand, fanned along an arc.
const width = 200
for (const [at, [name, angle]] of FAN.entries()) {
  const lift = Math.round(Math.abs(at - 2) * 18)
  pieces.push({
    input: await card(name, width, angle),
    left: 250 + at * 160,
    top: 400 + lift,
  })
}

await sharp(cover).composite(pieces).png({ palette: true, effort: 9 }).toFile(OUT)

const { size } = await sharp(OUT).metadata()
console.log(`${OUT}  ${WIDTH}x${HEIGHT}  ${Math.round((size ?? 0) / 1024)}KB`)
