#!/usr/bin/env bun
/**
 * Lists every animation clip an XP body can play, so the editor can offer them.
 *
 *     bun run xp:clips
 *
 * Run it after adding a clip file to `public/xp/packs/animation/`, or after
 * changing which of them the runtime loads. The output is checked in.
 *
 * ---------------------------------------------------------------------------
 * Only the files the runtime actually loads
 * ---------------------------------------------------------------------------
 * The pack ships eight glTFs and 139 clips; `skinned.tsx` loads three of them,
 * because each one is a download in front of a player and most levels use a
 * walk and an idle. So the honest list is not "what the pack contains" but
 * **what a body can play today** — a picker offering `Sit_Chair_Idle` from a
 * file nobody fetches is a picker that produces a body silently keeping its
 * last pose, which is exactly the failure `motion.ts` warns about.
 *
 * `SOURCES` is therefore read from the runtime rather than repeated here: the
 * two cannot disagree, and adding a file to that array is what makes its clips
 * appear in the editor.
 *
 * ---------------------------------------------------------------------------
 * Reading a GLB without a glTF loader
 * ---------------------------------------------------------------------------
 * A `.glb` is a twelve-byte header and then chunks; the first is the JSON, and
 * `animations[].name` is in it. That is the whole read — no three.js, no
 * loader, no WebGL, which is what makes this runnable in a script and in a test.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const ROOT = path.join(import.meta.dir, '..')
const PUBLIC = path.join(ROOT, 'public')
const OUT = path.join(ROOT, 'src', 'app', 'xp', '_runtime', 'clips.generated.ts')

/** The clip names in a `.glb`, in the order the file lists them. */
export function clipsIn(file: string): string[] {
  const buffer = readFileSync(file)
  // magic, version, length, then chunk length + type + data.
  if (buffer.readUInt32LE(0) !== 0x46546c67) throw new Error(`not a glb: ${file}`)
  const length = buffer.readUInt32LE(12)
  const type = buffer.readUInt32LE(16)
  // 0x4e4f534a is 'JSON'. It is required to be the first chunk.
  if (type !== 0x4e4f534a) throw new Error(`first chunk is not JSON: ${file}`)
  const json = JSON.parse(buffer.subarray(20, 20 + length).toString('utf8')) as {
    animations?: { name?: string }[]
  }
  return (json.animations ?? [])
    .map((animation) => animation.name)
    .filter((name): name is string => typeof name === 'string' && name.length > 0)
}

/**
 * The files the runtime loads, read out of the runtime.
 *
 * A regex over `skinned.tsx` rather than an import, because that module pulls
 * three.js and drei in and this script has no DOM. The shape it matches is the
 * `SOURCES` array's own template strings.
 */
export function runtimeSources(): string[] {
  const source = readFileSync(
    path.join(ROOT, 'src', 'app', 'xp', '_runtime', 'body', 'skinned.tsx'),
    'utf8',
  )
  const clips = /const CLIPS = '([^']+)'/.exec(source)?.[1]
  const block = /const SOURCES = \[([\s\S]*?)\]/.exec(source)?.[1]
  if (!clips || !block) throw new Error('skinned.tsx no longer declares CLIPS and SOURCES')
  return [...block.matchAll(/\$\{CLIPS\}\/([\w.]+)/g)].map((match) => `${clips}/${match[1]}`)
}

/** Every clip a body can play, sorted, with no duplicates across files. */
export function readClips(): string[] {
  const names = new Set<string>()
  for (const url of runtimeSources()) {
    for (const name of clipsIn(path.join(PUBLIC, url))) names.add(name)
  }
  return [...names].sort()
}

if (import.meta.main) {
  const clips = readClips()
  const body = `/**
 * Generated by \`bun run xp:clips\`. Do not edit.
 *
 * Every animation clip a body can play — the names in the glTFs \`skinned.tsx\`
 * loads, and only those. A name outside this list plays nothing and leaves the
 * body in its last pose, which is why the editor offers a list rather than a
 * text field.
 */

export const CLIPS = ${JSON.stringify(clips, null, 2)} as const

export type Clip = (typeof CLIPS)[number]
`
  writeFileSync(OUT, body)
  console.log(`${clips.length} clips → ${path.relative(ROOT, OUT)}`)
}
